export const mockUsers = [
    {
        id: 1,
        email: 'emp@example.com',
        password: 'password123',
        name: 'John Doe',
        role: 'employee',
        department: 'Engineering',
        position: 'Software Engineer',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=John',
    },
    {
        id: 2,
        email: 'manager@example.com',
        password: 'password123',
        name: 'Sarah Smith',
        role: 'manager',
        department: 'Engineering',
        position: 'Engineering Manager',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    },
    {
        id: 3,
        email: 'admin@example.com',
        password: 'password123',
        name: 'Admin User',
        role: 'admin',
        department: 'HR',
        position: 'HR Administrator',
        avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Admin',
    },
]

export const employeeList = [
    {
        id: 1,
        name: 'John Doe',
        department: 'Engineering',
        stress: 65,
        mood: 7,
        status: 'Active',
        lastCheck: '2024-03-26 10:30',
    },
    {
        id: 2,
        name: 'Emma Wilson',
        department: 'Engineering',
        stress: 78,
        mood: 5,
        status: 'Alert',
        lastCheck: '2024-03-26 09:15',
    },
    {
        id: 3,
        name: 'Michael Brown',
        department: 'Engineering',
        stress: 45,
        mood: 8,
        status: 'Active',
        lastCheck: '2024-03-26 11:00',
    },
    {
        id: 4,
        name: 'Lisa Anderson',
        department: 'Engineering',
        stress: 82,
        mood: 4,
        status: 'Alert',
        lastCheck: '2024-03-26 08:45',
    },
]